-- AlterTable
ALTER TABLE `User` ADD COLUMN `termosAceitosEm` DATETIME(3) NULL,
    ADD COLUMN `criadoDeIp` VARCHAR(191) NULL;

-- AlterTable
ALTER TABLE `Notificacao` MODIFY `tipo` ENUM('RECLAMACAO_PUBLICADA', 'RECLAMACAO_REJEITADA', 'RESPOSTA_OFICIAL', 'MUDANCA_STATUS', 'NOVO_COMENTARIO', 'PEDIDO_AVALIACAO', 'ATIVIDADE_SUSPEITA') NOT NULL;
